# version format
version: 1.3.5.{build}

image: Visual Studio 2019

cache:
  - packages -> **\packages.config
  - c:\projects\umbracoworkflow\preflight\node_modules -> **\packages.json
  
install:
  - set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe;C:\Ruby25\bin;%PATH%
  - cmd: npm install -g grunt-cli
  - cmd: set UMBRACO_PACKAGE_MIN_VERSION=8.1.0
  - cmd: nuget restore
  - cmd: cd BuildPackage
  - cmd: Build.bat
  
branches:
  only: 
  - master

test: off
build: off

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip
  
deploy:
  - provider: NuGet
    server:
    api_key:
      secure: 5jsE/ZahyaA4vVxXlV42s/fVWsAHB9qHoF3pwyUdqCfgOQJkesGcMLjEkUdwLhiG
    skip_symbols: false      
    symbol_server:    
    artifact: /.*\.nupkg/
    on:
        branch: master
        appveyor_repo_tag: true      
    
  - provider: GitHub
    tag: v1.3.5
    release: Release 1.3.5
    description: ""
    force_update: true
    auth_token:
        secure: Otbl8p8qCwciDqJgSWCyN0Arfs5XS1CwiHcK+r0F6uz9Rxt4gzBFvlc3cjPV3NxR
    artifact: /.*\.zip/     
    on:
        branch: master
        appveyor_repo_tag: true    
